<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Setting extends Model
{
    use HasFactory;

    protected $fillable = [
        'status',
        'groom_fullname',
        'groom_nickname',
        'groom_about',
        'groom_tiktok',
        'groom_facebook',
        'groom_instagram',
        'groom_picture',
        'bride_fullname',
        'bride_nickname',
        'bride_about',
        'bride_tiktok',
        'bride_facebook',
        'bride_instagram',
        'bride_picture',
        'home_couple_picture',
        'about_us_bg',
        'first_meet_date',
        'first_meet_picture',
        'first_meet_about',
        'first_date_date',
        'first_date_picture',
        'first_date_about',
        'engagement_date',
        'engagement_picture',
        'engagement_about',
        'event_bg',
        'event_ceremonial_date',
        'event_ceremonial_start_time',
        'event_ceremonial_end_time',
        'event_ceremonial_address',
        'event_ceremonial_link',
        'event_party_date',
        'event_party_start_time',
        'event_party_end_time',
        'event_party_address',
        'event_party_link',
        'event_traditional_date',
        'event_traditional_start_time',
        'event_traditional_end_time',
        'event_traditional_address',
        'event_traditional_link',
        'accompanist_fullname_1',
        'accompanist_type_1',
        'accompanist_status_1',
        'accompanist_tiktok_1',
        'accompanist_facebook_1',
        'accompanist_instagram_1',
        'accompanist_picture_1',
        'accompanist_fullname_2',
        'accompanist_type_2',
        'accompanist_status_2',
        'accompanist_tiktok_2',
        'accompanist_facebook_2',
        'accompanist_instagram_2',
        'accompanist_picture_2',
        'accompanist_fullname_3',
        'accompanist_type_3',
        'accompanist_status_3',
        'accompanist_tiktok_3',
        'accompanist_facebook_3',
        'accompanist_instagram_3',
        'accompanist_picture_3',
        'accompanist_fullname_4',
        'accompanist_type_4',
        'accompanist_status_4',
        'accompanist_tiktok_4',
        'accompanist_facebook_4',
        'accompanist_instagram_4',
        'accompanist_fullname_5',
        'accompanist_type_5',
        'accompanist_status_5',
        'accompanist_tiktok_5',
        'accompanist_facebook_5',
        'accompanist_instagram_5',
        'accompanist_picture_5',
        'accompanist_fullname_6',
        'accompanist_type_6',
        'accompanist_status_6',
        'accompanist_tiktok_6',
        'accompanist_facebook_6',
        'accompanist_instagram_6',
        'accompanist_picture_6',
        'gallery_1',
        'gallery_2',
        'gallery_3',
        'gallery_4',
        'gallery_5',
        'reservation_bg',
    ];
}
